"rectype","issueid","project_owner","project_name","actor","time","text","action","title"
"issue_title","872","nilearn","nilearn","dohmatob","2015-12-02 13:57:52","``` python
import numpy as np
from nilearn._utils.extmath import fast_abs_percentile
fast_abs_percentile(np.arange(4))
```

```
IndexError                                Traceback (most recent call last)
<ipython-input-29-094589b8fe4e> in <module>()
----> 1 fast_abs_percentile(arange(4))

/home/elvis/CODE/FORKED/nilearn/nilearn/_utils/extmath.pyc in fast_abs_percentile(data, percentile)
     43     if partition is not None:
     44         # Partial sort: faster than sort
---> 45         return partition(data, index)[index + 1]
     46     data.sort()
     47     return data[index + 1]

IndexError: index out of bounds
> /home/elvis/CODE/FORKED/nilearn/nilearn/_utils/extmath.py(45)fast_abs_percentile()
     44         # Partial sort: faster than sort
---> 45         return partition(data, index)[index + 1]
     46     data.sort()
```

This bug affects all the `find_cuts` functions of the plotting backend.
","start issue","Bug: IndexError in fast_abs_percentile function"
"issue_closed","872","nilearn","nilearn","dohmatob","2015-12-03 18:41:11","","closed issue","Bug: IndexError in fast_abs_percentile function"
