"rectype","issueid","project_owner","project_name","actor","time","text","action","title"
"issue_title","920","nilearn","nilearn","GaelVaroquaux","2015-12-18 07:10:48","A fix to cast/type issue in high_variance confounds #896
","start issue","[MRG]: fixing cast/type issue in high_variance confounds #896"
"issue_closed","920","nilearn","nilearn","GaelVaroquaux","2015-12-20 09:51:12","","closed issue","[MRG]: fixing cast/type issue in high_variance confounds #896"
"pull_request_title","920","nilearn","nilearn","GaelVaroquaux","2015-12-18 07:10:48","A fix to cast/type issue in high_variance confounds #896
","2ee156f915fa823dd14caabc8d5de00a998200d3","[MRG]: fixing cast/type issue in high_variance confounds #896"
"pull_request_merged","920","nilearn","nilearn","GaelVaroquaux","2015-12-20 09:51:12","[MRG]: fixing cast/type issue in high_variance confounds #896","1053f4add52b37357eaf087f88ee719466fbb0b8","Pull request merge from GaelVaroquaux/nilearn:fix_detrend_int to nilearn/nilearn:master"
"issue_comment","920","nilearn","nilearn","AlexandreAbraham","2015-12-18 07:31:54","+1
","",""
"issue_comment","920","nilearn","nilearn","AlexandreAbraham","2015-12-18 16:07:29","Yes, sorry, I am now used to failing appveyor with no reason...
","",""
"issue_comment","920","nilearn","nilearn","GaelVaroquaux","2015-12-18 07:28:47","This is now an MRG
","",""
"issue_comment","920","nilearn","nilearn","lesteve","2015-12-18 15:22:54","The AppVeyor tests seem like a genuine error to me:

```
======================================================================
FAIL: Test custom detrend implementation.
----------------------------------------------------------------------
Traceback (most recent call last):
  File ""C:\Miniconda3-x64\lib\site-packages\nose\case.py"", line 198, in runTest
    self.test(*self.arg)
  File ""C:\Miniconda3-x64\lib\site-packages\nilearn\tests\test_signal.py"", line 222, in test_detrend
    < 15. * np.finfo(np.float).eps)
AssertionError: False is not true
```
","",""
"issue_comment","920","nilearn","nilearn","GaelVaroquaux","2015-12-18 20:23:19","I fixed the AppVeyoer problem.
","",""
"issue_comment","920","nilearn","nilearn","bthirion","2015-12-20 09:50:45","LGTM.
","",""
"pull_request_commit","920","nilearn","nilearn","GaelVaroquaux","2015-12-18 07:09:48","BUG: a test that should fail on recent numpy?

Commit to test on travis","059aa04e5db961c820fcf1e120ef73be232b6f51",""
"pull_request_commit","920","nilearn","nilearn","GaelVaroquaux","2015-12-18 07:19:21","FIX: convert to float in detrend

Fixes #896","8d4841efb07343efd94c2e56c710a1f125e80a2a",""
"pull_request_commit","920","nilearn","nilearn","GaelVaroquaux","2015-12-18 18:29:10","FIX: adapt numerical precision for windows

This might make the tests pass under AppVeyor","2ee156f915fa823dd14caabc8d5de00a998200d3",""
