"rectype","issueid","project_owner","project_name","actor","time","text","action","title"
"issue_title","836","nilearn","nilearn","lesteve","2015-11-09 14:43:07","The segmentation fault happens after running the tests. I was able to reproduce it on my laptop.

For now we don't install matplotlib on AppVeyor meaning that the plotting tests are not run. This was a stop-gap solution to get the AppVeyor continuous integration up and running.

A few of suggestions:
- try to install matplotlib with conda rather than pip. Full disclosure I had trouble when doing that on my laptop (unable to import matplotlib._png if I remember correctly), but it's worth a try.
- try to install different matplotlib/numpy versions to see whether the problem persists.
","start issue","Segmentation fault on AppVeyor when installing matplotlib"
"issue_closed","836","nilearn","nilearn","lesteve","2015-11-19 09:06:47","","closed issue","Segmentation fault on AppVeyor when installing matplotlib"
"issue_comment","836","nilearn","nilearn","aabadie","2015-11-12 16:17:07","If you agree, I'll have a look at this issue in the coming days
","",""
"issue_comment","836","nilearn","nilearn","GaelVaroquaux","2015-11-12 16:37:35","> If you agree, I'll have a look at this issue in the coming days

That would be great. Maybe report upstream on the matplotlib tracker, if
you can get a good reproducible case and a c-level stack trace.
","",""
