"rectype","issueid","project_owner","project_name","actor","time","text","action","title"
"issue_title","274","pycqa","astroid","pylint-bot","2015-12-01 00:03:37","Originally reported by: **Brian Lane (BitBucket: [bcl](http://bitbucket.org/bcl), GitHub: @bcl?)**

---

I ran into a couple of test failures:

LoadModuleFromPathTest was failing on the 2nd pass because sys.just_once had been deleted.

In AstroidManagerTest there may be other hooks already present, so deleting 0 isn't correct. Removing -1 would likely work, but we may as well just look up the index and use that.

---
- Bitbucket: https://bitbucket.org/logilab/astroid/issue/274
","start issue","Test failures with Python 3.5"
"issue_closed","274","pycqa","astroid","ceridwen","2016-01-19 00:09:13","","closed issue","Test failures with Python 3.5"
"issue_comment","274","pycqa","astroid","pylint-bot","2015-11-30 23:12:59","_Original comment by_ **Claudiu Popa (BitBucket: [PCManticore](http://bitbucket.org/PCManticore), GitHub: @PCManticore)**:

---

Weird, nothing fails for me or in the CI. Could you send this as a PR? Thanks!
","",""
"issue_comment","274","pycqa","astroid","bcl","2015-12-10 22:54:10","Ends up this was because I was using setup.py test instead of tox.
","",""
